import '../lib/puppeteer-env.js';
import puppeteer, { type Browser, type Page } from 'puppeteer';
import { existsSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { PDFDocument } from 'pdf-lib';
import type { PdfOptions, Thread } from '@thread-to-pdf/shared';
import { config } from '../config.js';
import { ensurePuppeteerCacheEnv } from '../lib/puppeteer-env.js';
import { buildThreadHtml } from './html-builder.js';
import { startAssetServer, type AssetServer } from './asset-server.js';
import { cleanupThreadAssets, prepareThreadAssets } from './image-assets.js';
import { AppError } from '../lib/errors.js';

let browserInstance: Browser | null = null;

export function getChromeExecutablePath(): string | undefined {
  ensurePuppeteerCacheEnv();

  if (process.env.PUPPETEER_EXECUTABLE_PATH && existsSync(process.env.PUPPETEER_EXECUTABLE_PATH)) {
    return process.env.PUPPETEER_EXECUTABLE_PATH;
  }

  try {
    const path = puppeteer.executablePath();
    if (path && existsSync(path)) return path;
  } catch {
    // fall through
  }

  return undefined;
}

function getChromePath(): string | undefined {
  return getChromeExecutablePath();
}

export async function getBrowser(): Promise<Browser> {
  if (browserInstance?.connected) {
    return browserInstance;
  }

  const executablePath = getChromePath();
  if (!executablePath) {
    throw new AppError(
      'CHROME_NOT_INSTALLED',
      config.nodeEnv === 'production'
        ? 'PDF generation is not ready on the server yet. Wait a minute and try again.'
        : 'Chrome is not installed for PDF generation. Run: cd apps/server && npx puppeteer browsers install chrome',
      503,
    );
  }

  try {
    browserInstance = await puppeteer.launch({
      headless: true,
      executablePath,
      protocolTimeout: 120_000,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu',
        '--font-render-hinting=none',
      ],
    });
  } catch (error) {
    browserInstance = null;
    const message = error instanceof Error ? error.message : 'Unknown error';
    throw new AppError(
      'INTERNAL_ERROR',
      `Could not start Chrome for PDF generation: ${message}`,
      503,
    );
  }

  return browserInstance;
}

export async function closeBrowser(): Promise<void> {
  if (browserInstance) {
    await browserInstance.close();
    browserInstance = null;
  }
}

async function embedMetadata(
  pdfBuffer: Buffer,
  thread: Thread,
): Promise<Buffer> {
  const pdfDoc = await PDFDocument.load(pdfBuffer);
  const now = new Date();

  pdfDoc.setTitle(thread.title);
  pdfDoc.setAuthor('Generated by Thread to PDF');
  pdfDoc.setCreator('Thread to PDF');
  pdfDoc.setProducer('Thread to PDF');
  pdfDoc.setCreationDate(now);
  pdfDoc.setModificationDate(now);

  const bytes = await pdfDoc.save();
  return Buffer.from(bytes);
}

async function waitForImages(page: Page): Promise<void> {
  const deadline = Date.now() + 10_000;

  while (Date.now() < deadline) {
    const allLoaded = await page.evaluate(
      `Array.from(document.images).every(function(img) {
        return img.complete && img.naturalWidth > 0;
      })`,
    );

    if (allLoaded) return;
    await new Promise((resolve) => setTimeout(resolve, 200));
  }
}

export async function generatePdf(
  thread: Thread,
  options: Required<PdfOptions>,
): Promise<Buffer> {
  const { thread: preparedThread, assetsDir } = await prepareThreadAssets(thread);
  const html = buildThreadHtml(preparedThread, options);
  await writeFile(join(assetsDir, 'index.html'), html, 'utf8');

  let page: Page | undefined;
  let assetServer: AssetServer | undefined;

  try {
    assetServer = await startAssetServer(assetsDir);
    const browser = await getBrowser();
    page = await browser.newPage();

    await page.goto(`http://127.0.0.1:${assetServer.port}/index.html`, {
      waitUntil: 'networkidle0',
      timeout: 90_000,
    });

    await Promise.race([
      page.evaluate(() => document.fonts.ready),
      new Promise((resolve) => setTimeout(resolve, 5_000)),
    ]);

    await waitForImages(page);

    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '72px',
        right: '64px',
        bottom: '72px',
        left: '64px',
      },
      displayHeaderFooter: options.pageNumbers,
      headerTemplate: '<span></span>',
      footerTemplate: options.pageNumbers
        ? `<div style="width: 100%; font-size: 11px; color: #9ca3af; text-align: center; font-family: system-ui, sans-serif;">
            <span class="pageNumber"></span>
          </div>`
        : '<span></span>',
    });

    return await embedMetadata(Buffer.from(pdfBuffer), thread);
  } catch (error) {
    if (error instanceof AppError) throw error;

    const message = error instanceof Error ? error.message : 'Unknown error';
    throw new AppError(
      'INTERNAL_ERROR',
      `Failed to generate PDF: ${message}`,
      500,
    );
  } finally {
    if (page) await page.close().catch(() => undefined);
    if (assetServer) await assetServer.close().catch(() => undefined);
    await cleanupThreadAssets(assetsDir);
  }
}
